# This workflow will do a clean install of node dependencies
# and test/build the project.

name: ci

on:
  push:
    branches: [ main, next, dev ]
  pull_request:
    branches: [ main, next, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.14]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci && npm run integration
